### Author: Frish2021 ###
name: build_1_21_1

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Mint-jar
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.5.0
      with: 
        java-version: '21'
        distribution: 'temurin'
        architecture: x64

    - name: Config Git
      run: git config --global user.email "CI@menthamc.com" && git config --global user.name "MenthaMC CI"

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Apply Patches
      run: ./gradlew applyPatches

    - name: Build jar
      run: ./gradlew createMojmapPaperclipJar

    - name: Upload artifacts
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: '1.21.1-R0.1-SNAPSHOT'
        name: 'Mint-1.21.1-R0.1-SNAPSHOT'
        files: 'build/libs/**'
