### Author: Frish2021 ###
name: build_1_21

on:
  push:
    paths:
      - 'patches/**'
      - 'gradle.properties'
      - 'gradle/wrapper/gradle-wrapper.properties'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'zulu'
          architecture: x64

      - name: Config Git
        run: |
          git config --global user.email "CI@menthamc.com"
          git config --global user.name "MenthaMC-CI"

      - name: Building Mint...
        run: |
          chmod +x ./gradlew
          ./gradlew applyPatches
          ./gradlew createMojmapPaperclipJar

      - name: Set Env
        run: |
          echo "commit_tag=$(git log --pretty='%h' -1)" >> $GITHUB_ENV
          echo "commit_msg=$(git log --pretty='> [%h] %s' -1)" >> $GITHUB_ENV
          echo "branch_name=$(git branch --show-current)" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.commit_tag }}
          name: 'Mint 1.21 - ${{ env.commit_tag }} - ${{ env.branch_name }}'
          body: |
            📦Version: `1.21 - ${{ env.commit_tag }}`
            ![version](https://img.shields.io/badge/version-1.21_R0.1_SNAPSHOT-light_green?style=flat-square)
            ![downloads](https://img.shields.io/github/downloads/MenthaMC/Mint/${{ env.commit_tag }}/total?style=flat-square)
            ### Update Message
            ${{ env.commit_msg }}
          files: 'build/libs/*.jar'
