### Author: Frish2021 ###
name: publish_1_21

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish Mint packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'zulu'
          architecture: x64

      - name: Config Git
        run: git config --global user.email "CI@menthamc.com" && git config --global user.name "MenthaMC CI"

      - name: Make gradlew executable
        run: chmod +x ./gradlew
  
      - name: Apply Patches
        run: ./gradlew applyPatches

      - name: Publish package
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
