### Author: Frish2021 ###
name: publish_1_21_1

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish Mint-api Jar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'zulu'
          architecture: x64

      - name: Publish package
        run: chmod +x ./gradlew && ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
